- [ZBX-3479] merge from branches/1.8
git-svn-id: svn://svn.zabbix.com/branches/dev@17582 f4e7fd02-d210-4e34-a1e0-d4093fb66cc2

diff --git a/ZBX-3479/upgrades/dbpatches/1.8/mysql/upgrade b/ZBX-3479/upgrades/dbpatches/1.8/mysql/upgrade
--- a/ZBX-3479/upgrades/dbpatches/1.8/mysql/upgrade
+++ b/ZBX-3479/upgrades/dbpatches/1.8/mysql/upgrade
@@ -40,6 +40,7 @@ fail() {
 }
 
 [[ "$MYSQL" ]] || fail "No mysql binary in path."
+[[ -f "patch.sql" ]] || fail "File patch.sql not found."
 
 timer() {
 	TIMER=$(echo "$@" | cut -d" " -f 2- | tr " " _)
@@ -61,14 +62,14 @@ increaseid() {
 # increases corresponding id if found, searches the table for max id and inserts one if not
 # returns freshly inserted id to be used with new entry
 	CURRENTID=$(echo "select nextid from ids where table_name='$1' and field_name='$2';" | $MYSQL $MYSQLPARAMS -N)
-	
+
 	[[ "$CURRENTID" ]] && {
 		echo "update ids set nextid='$[$CURRENTID+1]' where table_name='$1' and field_name='$2';" | $MYSQL $MYSQLPARAMS
 	} || {
 		CURRENTID=$(echo "select $2 from $1 order by $2 desc limit 1;" | $MYSQL $MYSQLPARAMS -N)
 		echo "insert into ids values (0,'$1','$2',$[$CURRENTID+1]);" | $MYSQL $MYSQLPARAMS
 	}
-	return $[$CURRENTID+1]
+	echo $[$CURRENTID+1]
 }
 
 drop_index() {
@@ -122,12 +123,12 @@ timer stop patching of the database
 
 # ********************   4
 
-echo "Adding 'Discovered Hosts' host group"
+echo "Adding 'Discovered hosts' host group"
 
-increaseid groups groupid
+discoveredhostsgroup=$(increaseid groups groupid)
 
-echo "update config set discovery_groupid=(select nextid from ids where table_name='groups' and field_name='groupid') where configid='1';
-insert into groups (groupid,name,internal) select nextid,'Discovered Hosts','1' from ids where table_name='groups' and field_name='groupid';" | $MYSQL $MYSQLPARAMS
+echo "update config set discovery_groupid='$discoveredhostsgroup' where configid='1';
+insert into groups (groupid,name,internal) values ('$discoveredhostsgroup','Discovered hosts','1');" | $MYSQL $MYSQLPARAMS
 
 # ********************   5
 
@@ -137,8 +138,8 @@ echo -n "Checking for 'Disabled' user group... "
 	echo "found, not doing anything."
 } || {
 	echo "not found, adding."
-	increaseid usrgrp usrgrpid
-	echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) select nextid,'Disabled','0','1','0','0' from ids where table_name='usrgrp' and field_name='usrgrpid';" | $MYSQL $MYSQLPARAMS
+	disabledusrgroup=$(increaseid usrgrp usrgrpid)
+	echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) values ('$disabledusrgroup','Disabled','0','1','0','0');" | $MYSQL $MYSQLPARAMS
 }
 
 # ********************   6
@@ -156,11 +157,11 @@ HOSTSWOGROUP=$(echo "select hosts.hostid from hosts left join hosts_groups on ho
 	} || {
 		echo "Group '$GROUPFORHOSTS' does not exist, creating it and adding all orphaned hosts to it."
 		GROUPFORHOSTSID=$(increaseid groups groupid)
-		echo "insert into groups (groupid,name,internal) select nextid,'$GROUPFORHOSTS','0' from ids where table_name='groups' and field_name='groupid';" | $MYSQL $MYSQLPARAMS
+		echo "insert into groups (groupid,name,internal) values ('$GROUPFORHOSTSID','$GROUPFORHOSTS','0');" | $MYSQL $MYSQLPARAMS
 	}
 	for ORPHANHOST in $HOSTSWOGROUP; do
 		MAPPINGID=$(increaseid hosts_groups hostgroupid)
-		echo "insert into hosts_groups (hostgroupid,hostid,groupid) select nextid,'$ORPHANHOST','$GROUPFORHOSTSID' from ids where table_name='hosts_groups' and field_name='hostgroupid';" | $MYSQL $MYSQLPARAMS
+		echo "insert into hosts_groups (hostgroupid,hostid,groupid) values ('$MAPPINGID','$ORPHANHOST','$GROUPFORHOSTSID');" | $MYSQL $MYSQLPARAMS
 		((HOSTSADDED++))
 	done
 	echo "Added $HOSTSADDED hosts to group '$GROUPFORHOSTS'. Move them to correct groups manually."
