Advanced configre.in. Better support for MySQL and PostgreSQL environment.
git-svn-id: svn://svn.zabbix.com/trunk@150 97f52cf1-0a1b-0410-bd0e-c28be96e8082

diff --git a/src/zabbix_trapper/configure.in b/src/zabbix_trapper/configure.in
--- a/src/zabbix_trapper/configure.in
+++ b/src/zabbix_trapper/configure.in
@@ -6,8 +6,8 @@ AC_PROG_CC
 
 dnl Checks for libraries.
 dnl Replace `main' with a function in -lmysqlclient:
-AC_CHECK_LIB(mysqlclient, main)
-AC_CHECK_LIB(pq, main)
+dnl #AC_CHECK_LIB(mysqlclient, main)
+dnl #AC_CHECK_LIB(pq, main)
 
 dnl Checks for header files.
 AC_HEADER_STDC
@@ -16,11 +16,134 @@ AC_CHECK_HEADERS(stdio.h stdlib.h unistd.h netdb.h signal.h \
   time.h syslog.h sys/types.h sys/stat.h netinet/in.h)
 
 dnl Checks for typedefs, structures, and compiler characteristics.
+AC_C_CONST
 AC_TYPE_PID_T
 
 dnl Checks for library functions.
 AC_TYPE_SIGNAL
 AC_CHECK_FUNCS(socket strtod)
 
+
+AC_MSG_CHECKING(for MySQL support)
+AC_ARG_WITH(mysql,
+[
+What DBMS do you want to use (please select only one):
+  --with-mysql[=DIR]      Include MySQL support.  DIR is the MySQL base
+                          install directory, default is to search through
+                          a number of common places for the MySQL files.],
+[
+  if test "$withval" != "no"; then
+  	if test "$withval" = "yes"; then
+		if test -f /usr/local/mysql/include/mysql/mysql.h; then
+			MYSQL_INCDIR=/usr/local/mysql/include/mysql
+			MYSQL_LIBDIR=/usr/local/mysql/lib/mysql
+		elif test -f /usr/include/mysql/mysql.h; then
+			MYSQL_INCDIR=/usr/include/mysql
+			MYSQL_LIBDIR=/usr/lib/mysql
+		elif test -f /usr/include/mysql.h; then
+			MYSQL_INCDIR=/usr/include
+			MYSQL_LIBDIR=/usr/lib
+		elif test -f /usr/local/include/mysql/mysql.h; then
+			MYSQL_INCDIR=/usr/local/include/mysql
+			MYSQL_LIBDIR=/usr/local/lib/mysql
+		elif test -f /usr/local/include/mysql.h; then
+			MYSQL_INCDIR=/usr/local/include
+			MYSQL_LIBDIR=/usr/local/lib
+		else
+    		AC_MSG_RESULT(no)
+    		AC_MSG_ERROR(Invalid MySQL directory - unable to find mysql.h)
+		fi
+   	else
+		if test -f $withval/include/mysql/mysql.h; then
+   			MYSQL_INCDIR=$withval/include/mysql
+   			MYSQL_LIBDIR=$withval/lib/mysql
+		elif test -f $withval/include/mysql.h; then
+   			MYSQL_INCDIR=$withval/include
+   			MYSQL_LIBDIR=$withval/lib
+		else
+    		AC_MSG_RESULT(no)
+    		AC_MSG_ERROR(Invalid MySQL directory - unable to find mysql.h under $withval)
+		fi
+   	fi
+    MYSQL_INCLUDE=-I$MYSQL_INCDIR
+    MYSQL_LFLAGS="-L$MYSQL_LIBDIR -lmysqlclient"
+
+    AC_DEFINE(HAVE_MYSQL)
+    AC_MSG_RESULT(yes)
+    have_db=yes
+    dnl MySQL requires -lm sometime
+    AC_CHECK_FUNC(floor, , AC_CHECK_LIB(m, floor, MYSQL_LFLAGS="$MYSQL_LFLAGS -lm"))
+    dnl MySQL 3.23 requires -lz sometime
+    AC_CHECK_FUNC(compress, , AC_CHECK_LIB(z, compress, MYSQL_LFLAGS="$MYSQL_LFLAGS -lz"))
+
+  else
+  	AC_MSG_RESULT(no)
+  fi
+],[
+  AC_MSG_RESULT(no)
+])
+AC_SUBST(MYSQL_LFLAGS)
+AC_SUBST(MYSQL_INCLUDE)
+
+
+AC_MSG_CHECKING(for PostgreSQL support)
+AC_ARG_WITH(pgsql,
+[  --with-pgsql[=DIR]      Include PostgreSQL support.  DIR is the PostgreSQL
+                          base install directory, defaults to /usr/local/pgsql.],
+[
+  if test "$withval" != "no"; then
+      if test "$have_db" = "yes"; then
+          AC_MSG_RESULT(error)
+          AC_MSG_ERROR("You can configure for only one database.");
+      fi
+  	if test "$withval" = "yes"; then
+		if test -f /usr/include/pgsql/libpq-fe.h; then
+			PGSQL_INCDIR=/usr/include/pgsql
+		elif test -f /usr/include/postgresql/libpq-fe.h; then
+			PGSQL_INCDIR=/usr/include/postgresql
+		else
+			PGSQL_INCDIR=/usr/local/pgsql/include
+		fi
+		if test -f /usr/lib/libpq.a; then
+			PGSQL_LIBDIR=/usr/lib
+		else
+			PGSQL_LIBDIR=/usr/local/pgsql/lib
+		fi
+   	else
+   		PGSQL_INCDIR=$withval/include
+   		test -d $withval/include/pgsql && PGSQL_INCDIR=$withval/include/pgsql
+   		PGSQL_LIBDIR=$withval/lib
+   		test -d $withval/lib/pgsql && PGSQL_LIBDIR=$withval/lib/pgsql
+   	fi
+    PGSQL_INCLUDE=-I$PGSQL_INCDIR
+    PGSQL_LFLAGS="-L$PGSQL_LIBDIR -lpq"
+    AC_CHECK_FUNC(crypt, , AC_CHECK_LIB(crypt, crypt, LIBS="-lcrypt $LIBS"))
+
+    AC_DEFINE(HAVE_PGSQL)
+    AC_MSG_RESULT(yes)
+    have_db=yes
+  else
+    AC_MSG_RESULT(no)
+  fi
+],[
+  AC_MSG_RESULT(no)
+])
+AC_SUBST(PGSQL_LFLAGS)
+AC_SUBST(PGSQL_INCLUDE)
+
+if test "$have_db" != "yes"; then
+	{ echo "configure: error: No database selected! Use --with-XXX where XXX is your preferred database type" 1>&2; exit 1; }
+echo
+fi
+
 AC_CONFIG_HEADER(config.h)
 AC_OUTPUT(Makefile)
+
+echo
+echo "***********************************************************"
+echo "*            Now run make                                 *"
+echo "*                                                         *"
+echo "*            Thank you for using Zabbix !                 *"
+echo "*          <http://zabbix.sourceforge.net>                *"
+echo "***********************************************************"
+echo
