- [ZBX-1419] also add user groups 'API access' and 'Debug' if they are missing; use associated arrays for bash >= 4.1, hackish solution for older versions

diff --git a/upgrades/dbpatches/2.0/mysql/upgrade b/upgrades/dbpatches/2.0/mysql/upgrade
--- a/upgrades/dbpatches/2.0/mysql/upgrade
+++ b/upgrades/dbpatches/2.0/mysql/upgrade
@@ -6,7 +6,7 @@ echo " WARNING: backup your database before performing upgrade
  It does the following things:
   1. Updates indexes that might require changes;
   2. Patches the database from 1.8 schema to 2.0 schema;
-  3. Adds 'Disabled' usergroup if it is missing;
+  3. Adds 'Disabled', 'API access' and 'Debug' usergroup if any missing;
   4. Checks for hosts not belonging to any group and adds them to one if any found.
 
  Usage: pass required MySQL parameters to this script (like database, user, password etc).
@@ -103,14 +103,54 @@ timer stop patching of the database
 
 # ********************   3
 
-echo -n "Checking for 'Disabled' user group... "
+[[ "$(echo $BASH_VERSION | cut -d. -f1,2 )" < "4.1" ]] && {{
+	# bash < 4.1 version
+	echo "bash < 4.1 detected"
+	# groupname,columnname
+	for group in "Disabled,users_status" "API access,api_access" "Debug,debug_mode"; do
+		groupname=$(echo $group | cut -d, -f1)
+		column=$(echo $group | cut -d, -f2)
+		echo -n "Checking for '$groupname' user group... "
 
-[[ "$(echo "select name from usrgrp where name='Disabled';" | $MYSQL $MYSQLPARAMS -N)" ]] && {
-	echo "found, not doing anything."
+		[[ "$(echo "select name from usrgrp where name='$groupname';" | $MYSQL $MYSQLPARAMS -N)" ]] && {
+			echo "found, not doing anything."
+		} || {
+			echo "not found, adding."
+			dbcolumn=$(echo $group | cut -d, -f2)
+			# avoiding eval
+			declare $dbcolumn=1
+			usrgrouptoadd=$(increaseid usrgrp usrgrpid)
+			echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) values ('$usrgrouptoadd','$groupname','0','$users_status','$api_access','$debug_mode');" | $MYSQL $MYSQLPARAMS
+			unset $dbcolumn
+		}
+	done
 } || {
-	echo "not found, adding."
-	disabledusrgroup=$(increaseid usrgrp usrgrpid)
-	echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) values ('$disabledusrgroup','Disabled','0','1','0','0');" | $MYSQL $MYSQLPARAMS
+	echo "bash >= 4.1 detected"
+	# bash >= 4.1 version
+	# ["groupname"]=columnname
+	# associative arrays supported since bash 4.0
+	# groups with spaces in their names don't work in bash 4.0 (works in 4.1)
+
+	declare -A groupstoadd
+	groupstoadd=(
+["Disabled"]=users_status
+["API access"]=api_access
+["Debug"]=debug_mode
+)
+
+	# loop over array keys
+	for groupname in "${!groupstoadd[@]}"; do
+		echo -n "Checking for '$groupname' user group... "
+		[[ "$(echo "select name from usrgrp where name='$groupname';" | $MYSQL $MYSQLPARAMS -N)" ]] && {
+			echo "found, not doing anything."
+		} || {
+			echo "not found, adding."
+			declare ${groupstoadd[$groupname]}=1
+			usrgrouptoadd=$(increaseid usrgrp usrgrpid)
+			echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) values ('$usrgrouptoadd','$groupname','0','$users_status','$api_access','$debug_mode');" | $MYSQL $MYSQLPARAMS
+			unset ${groupstoadd[$groupname]}
+		}
+	done
 }
 
 # ********************   4
