- [ZBX-3358] Sync with trunk
git-svn-id: svn://svn.zabbix.com/branches/dev@17764 f4e7fd02-d210-4e34-a1e0-d4093fb66cc2

diff --git a/ZBX-3358/upgrades/dbpatches/2.0/mysql/upgrade b/ZBX-3358/upgrades/dbpatches/2.0/mysql/upgrade
--- a/ZBX-3358/upgrades/dbpatches/2.0/mysql/upgrade
+++ b/ZBX-3358/upgrades/dbpatches/2.0/mysql/upgrade
@@ -6,7 +6,7 @@ echo " WARNING: backup your database before performing upgrade
  It does the following things:
   1. Updates indexes that might require changes;
   2. Patches the database from 1.8 schema to 2.0 schema;
-  3. Adds 'Disabled' usergroup if it is missing;
+  3. Adds 'Disabled', 'API access' and 'Debug' usergroup if any missing;
   4. Checks for hosts not belonging to any group and adds them to one if any found.
 
  Usage: pass required MySQL parameters to this script (like database, user, password etc).
@@ -53,14 +53,14 @@ increaseid() {
 # increases corresponding id if found, searches the table for max id and inserts one if not
 # returns freshly inserted id to be used with new entry
 	CURRENTID=$(echo "select nextid from ids where table_name='$1' and field_name='$2';" | $MYSQL $MYSQLPARAMS -N)
-	
+
 	[[ "$CURRENTID" ]] && {
 		echo "update ids set nextid='$[$CURRENTID+1]' where table_name='$1' and field_name='$2';" | $MYSQL $MYSQLPARAMS
 	} || {
 		CURRENTID=$(echo "select $2 from $1 order by $2 desc limit 1;" | $MYSQL $MYSQLPARAMS -N)
 		echo "insert into ids values (0,'$1','$2',$[$CURRENTID+1]);" | $MYSQL $MYSQLPARAMS
 	}
-	return $[$CURRENTID+1]
+	echo $[$CURRENTID+1]
 }
 
 drop_index() {
@@ -103,14 +103,54 @@ timer stop patching of the database
 
 # ********************   3
 
-echo -n "Checking for 'Disabled' user group... "
+[[ "$(echo $BASH_VERSION | cut -d. -f1,2 )" < "4.1" ]] && {
+	# bash < 4.1 version
+	echo "bash < 4.1 detected"
+	# groupname,columnname
+	for group in "Disabled,users_status" "API access,api_access" "Debug,debug_mode"; do
+		groupname=$(echo $group | cut -d, -f1)
+		column=$(echo $group | cut -d, -f2)
+		echo -n "Checking for '$groupname' user group... "
 
-[[ "$(echo "select name from usrgrp where name='Disabled';" | $MYSQL $MYSQLPARAMS -N)" ]] && {
-	echo "found, not doing anything."
+		[[ "$(echo "select name from usrgrp where name='$groupname';" | $MYSQL $MYSQLPARAMS -N)" ]] && {
+			echo "found, not doing anything."
+		} || {
+			echo "not found, adding."
+			dbcolumn=$(echo $group | cut -d, -f2)
+			# avoiding eval
+			declare $dbcolumn=1
+			usrgrouptoadd=$(increaseid usrgrp usrgrpid)
+			echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) values ('$usrgrouptoadd','$groupname','0','$users_status','$api_access','$debug_mode');" | $MYSQL $MYSQLPARAMS
+			unset $dbcolumn
+		}
+	done
 } || {
-	echo "not found, adding."
-	increaseid usrgrp usrgrpid
-	echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) select nextid,'Disabled','0','1','0','0' from ids where table_name='usrgrp' and field_name='usrgrpid';" | $MYSQL $MYSQLPARAMS
+	echo "bash >= 4.1 detected"
+	# bash >= 4.1 version
+	# ["groupname"]=columnname
+	# associative arrays supported since bash 4.0
+	# groups with spaces in their names don't work in bash 4.0 (works in 4.1)
+
+	declare -A groupstoadd
+	groupstoadd=(
+["Disabled"]=users_status
+["API access"]=api_access
+["Debug"]=debug_mode
+)
+
+	# loop over array keys
+	for groupname in "${!groupstoadd[@]}"; do
+		echo -n "Checking for '$groupname' user group... "
+		[[ "$(echo "select name from usrgrp where name='$groupname';" | $MYSQL $MYSQLPARAMS -N)" ]] && {
+			echo "found, not doing anything."
+		} || {
+			echo "not found, adding."
+			declare ${groupstoadd[$groupname]}=1
+			usrgrouptoadd=$(increaseid usrgrp usrgrpid)
+			echo "insert into usrgrp (usrgrpid,name,gui_access,users_status,api_access,debug_mode) values ('$usrgrouptoadd','$groupname','0','$users_status','$api_access','$debug_mode');" | $MYSQL $MYSQLPARAMS
+			unset ${groupstoadd[$groupname]}
+		}
+	done
 }
 
 # ********************   4
@@ -128,11 +168,11 @@ HOSTSWOGROUP=$(echo "select hosts.hostid from hosts left join hosts_groups on ho
 	} || {
 		echo "Group '$GROUPFORHOSTS' does not exist, creating it and adding all orphaned hosts to it."
 		GROUPFORHOSTSID=$(increaseid groups groupid)
-		echo "insert into groups (groupid,name,internal) select nextid,'$GROUPFORHOSTS','0' from ids where table_name='groups' and field_name='groupid';" | $MYSQL $MYSQLPARAMS
+		echo "insert into groups (groupid,name,internal) values ('$GROUPFORHOSTSID','$GROUPFORHOSTS','0');" | $MYSQL $MYSQLPARAMS
 	}
 	for ORPHANHOST in $HOSTSWOGROUP; do
 		MAPPINGID=$(increaseid hosts_groups hostgroupid)
-		echo "insert into hosts_groups (hostgroupid,hostid,groupid) select nextid,'$ORPHANHOST','$GROUPFORHOSTSID' from ids where table_name='hosts_groups' and field_name='hostgroupid';" | $MYSQL $MYSQLPARAMS
+		echo "insert into hosts_groups (hostgroupid,hostid,groupid) values ('$MAPPINGID','$ORPHANHOST','$GROUPFORHOSTSID');" | $MYSQL $MYSQLPARAMS
 		((HOSTSADDED++))
 	done
 	echo "Added $HOSTSADDED hosts to group '$GROUPFORHOSTS'. Move them to correct groups manually."
